version: '3.8'

services:
  painel-metas:
    image: mmpgnovaiscrud/painel-gdo-19bpm:v4
    container_name: metas_19bpm
    restart: always
    ports:
      - "80:80"
    volumes:
      # Opcional: Use este volume apenas quando quiser ATUALIZAR os dados 
      # trocando os arquivos na VPS, sem precisar gerar nova imagem Docker.
      - ./gdo_data:/usr/share/nginx/html/data